---
sidebar: sidebar 
permalink: docs/hci_prereqs_witness_nodes.html 
summary: Erfahren Sie mehr über die Anforderungen des NetApp HCI Witness Nodes. 
keywords: netapp, hci, element, Witness Node 
---
= Ressourcenanforderungen von Witness Node für Storage Cluster mit zwei Nodes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: netapp, hci, element, Witness Node


[role="lead"]
NetApp HCI unterstützt eine Mindestinstallationsgröße von zwei Storage-Nodes und zwei Computing-Nodes. Wenn Sie NetApp HCI mit einem Storage Cluster mit zwei oder drei Nodes installieren, müssen Sie die Ressourcenanforderungen der NetApp HCI Witness Nodes und der Virtual Machine (VM) kennen.

Wenn ein Storage-Cluster zwei oder drei Nodes verwendet, wird außerdem neben jedem Storage Cluster ein Paar Witness-Nodes implementiert. Witness-Nodes verfügen über die folgenden VM-Ressourcenanforderungen:

|===
| Ressource | Anforderungen 


| VCPU | 4 


| Speicher | 12 GB 


| Festplattengröße | 67 GB 
|===
NetApp HCI unterstützt nur bestimmte Storage-Node-Modelle in Storage-Clustern mit zwei oder drei Nodes. Weitere Informationen finden Sie in den Versionshinweisen für Ihre NetApp HCI-Version.

|===


 a| 
*Best Practice:* Konfigurieren Sie die Witness Node VMs so konfigurieren Sie den lokalen Datastore des Computing-Nodes (Standardeinstellung: Nde) und konfigurieren Sie diese nicht auf Shared Storage, z. B. SolidFire Storage Volumes. Um eine automatische Migration der VMs zu verhindern, stellen Sie die Automatisierungsebene des Distributed Resource Scheduler (DRS) der Witness Node VM auf *deaktivierte* ein. Dadurch wird verhindert, dass beide Witness-Nodes auf demselben Computing-Node ausgeführt werden und eine Konfiguration mit einem Hochverfügbarkeitspaar (HA-Paar) erstellt wird.

|===

NOTE: Wenn der Installationsprozess von NetApp HCI Witness Nodes installiert, wird eine VM-Vorlage in VMware vCenter gespeichert, mit der Sie einen Witness-Node neu bereitstellen können, falls dieser versehentlich entfernt, verloren oder beschädigt wurde. Sie können auch die Vorlage verwenden, um einen Witness Node neu zu implementieren, wenn ein ausgefallener Computing-Node, der den Witness Node hostet, ersetzt werden muss. Anweisungen hierzu finden Sie im Abschnitt * Witness Nodes für zwei und drei-Node-Storage-Cluster neu implementieren* link:task_hci_h410crepl.html["Hier"^].

[discrete]
== Weitere Informationen

* https://www.netapp.com/hybrid-cloud/hci-documentation/["Ressourcen-Seite zu NetApp HCI"^]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]

