---
sidebar: sidebar 
permalink: docs/reference_hcc_config_maximums.html 
summary: NetApp Hybrid Cloud Control verfügt über spezifische Funktionen und empfiehlt, innerhalb dieser Funktionen zu arbeiten. 
keywords: netapp, hci, HCC, configuration, capabilities, limits, maximums 
---
= Maximale Konfigurationswerte für NetApp Hybrid Cloud Control
:allow-uri-read: 


[role="lead"]
NetApp HCI umfasst NetApp Hybrid Cloud Control zur Vereinfachung von Computing-Lebenszyklus und Storage-Management. Die Lösung unterstützt Upgrades von Element Software auf Storage-Nodes für NetApp HCI und NetApp SolidFire Storage-Cluster sowie Firmware-Upgrades für NetApp HCI Computing-Nodes in NetApp HCI. Er ist standardmäßig auf den Management-Nodes in NetApp HCI verfügbar.

NetApp Hybrid Cloud Control kommuniziert nicht nur über die von NetApp bereitgestellten Hardware- und Software-Komponenten in einer NetApp HCI-Installation, sondern interagiert auch mit Komponenten anderer Anbieter in der Kundenumgebung wie VMware vCenter. NetApp stimmt die Funktionen von NetApp Hybrid Cloud Control und seine Interaktion mit diesen Drittanbieterkomponenten in der Kundenumgebung auf ein bestimmtes Maß ab. Für optimale Benutzerfreundlichkeit mit NetApp Hybrid Cloud Control empfiehlt NetApp, innerhalb verschiedener Konfigurationsmaxima zu bleiben.

Wenn Sie diese getesteten Grenzwerte überschreiten, treten möglicherweise Probleme mit NetApp Hybrid Cloud Control auf, z. B. eine langsamere Benutzeroberfläche, API-Antworten oder Funktionen, die nicht verfügbar sind. Wenn Sie NetApp für Produkt-Support mit NetApp Hybrid Cloud Control in Umgebungen einsetzen, die über die Konfigurationsmaxima hinausgehen, wird NetApp Support bitten, dass Sie die Konfiguration innerhalb der dokumentierten Konfigurationsmaxima ändern.

.Konfigurationsmaxima
NetApp Hybrid Cloud Control unterstützt VMware vSphere Umgebungen mit bis zu 500 NetApp Computing-Nodes. Es unterstützt bis zu 20 NetApp Element Software basierte Storage Cluster mit 40 Storage Nodes pro Cluster.
