---
sidebar: sidebar 
permalink: docs/task_mnode_add_assets.html 
summary: Über DIE REST API UI lassen sich Compute- und Controller-Ressourcen zur Management-Node-Konfiguration hinzufügen. 
keywords: netapp, mnode, management node, rest api, hci 
---
= Fügen Sie dem Management-Node Computing- und Controller-Ressourcen hinzu
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Über DIE REST API UI lassen sich Compute- und Controller-Ressourcen zur Management-Node-Konfiguration hinzufügen.

Möglicherweise müssen Sie ein Asset hinzufügen, wenn Sie vor Kurzem Ihre Installation skaliert haben und neue Ressourcen nicht automatisch zu Ihrer Konfiguration hinzugefügt wurden. Mithilfe dieser APIs können Sie Ressourcen hinzufügen, die zu Ihrer Installation hinzugefügt wurden.

.Was Sie benötigen
* In Ihrer Cluster-Version wird die NetApp Element Software 11.3 oder höher ausgeführt.
* Sie haben einen Management-Node mit Version 11.3 oder höher implementiert.
* Das ist schon link:task_mnode_create_netapp_hcc_role_vcenter.html["Neue NetApp HCC-Rolle in vCenter erstellt"] Begrenzung der Management-Node-Services-Ansicht auf reine NetApp Ressourcen
* Sie verfügen über die vCenter-Management-IP-Adresse und die zugehörigen Anmeldedaten.
* Sie haben die Management-IP-Adresse und die Root-Anmeldedaten des Computing-Nodes (ESXi).
* Sie verfügen über die Hardware- (BMC) Management-IP-Adresse und Administrator-Anmeldeinformationen.


.Über diese Aufgabe
(Nur NetApp HCI) Wenn nach der Skalierung Ihres NetApp HCI-Systems keine Computing-Nodes in der Hybrid Cloud Control (HCC) angezeigt werden, können Sie mithilfe der einen Compute-Node hinzufügen `POST /assets/{asset_id}/compute-nodes` Beschrieben in diesem Verfahren.


NOTE: Wenn Sie Computing-Knoten manuell hinzufügen, stellen Sie sicher, dass Sie auch die BMC-Assets hinzufügen. Andernfalls wird ein Fehler zurückgegeben.

.Schritte
. Holen Sie sich die Basis-Asset-ID für die Installation:
+
.. Öffnen Sie die REST API-UI für den Bestandsdienst auf dem Managementknoten:
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. Wählen Sie *autorisieren* aus, und füllen Sie Folgendes aus:
+
... Geben Sie den Benutzernamen und das Passwort für den Cluster ein.
... Geben Sie die Client-ID als ein `mnode-client`.
... Wählen Sie *autorisieren*, um eine Sitzung zu starten.
... Schließen Sie das Fenster.


.. Wählen Sie in DER REST API UI *GET ​/Installations* aus.
.. Wählen Sie *Probieren Sie es aus*.
.. Wählen Sie *Ausführen*.
.. Kopieren Sie aus dem Text Code 200 Antwort den `id` Für die Installation.
+
[listing, subs="+quotes"]
----
{
  "installations": [
    {
      "_links": {
        "collection": "https://10.111.211.111/inventory/1/installations",
        "self": "https://10.111.217.111/inventory/1/installations/abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x"
      },
      *"id": "abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x",*
----
+

NOTE: Die Installation verfügt über eine Basiskonfiguration, die während der Installation oder eines Upgrades erstellt wurde.

.. Wählen Sie in DER REST-API-UI *GET /installations/{id}* aus.
.. Wählen Sie *Probieren Sie es aus*.
.. Fügen Sie die Installations-Asset-ID in das Feld *id* ein.
.. Wählen Sie *Ausführen*.
.. Kopieren Sie aus der Antwort die Cluster-Controller-ID und speichern Sie sie (`"controllerId"`) Für den Einsatz in einem späteren Schritt.


. (Nur für Computing-Nodes) xref:task_mnode_locate_hardware_tag.adoc[Suchen Sie die Hardware-Tag-Nummer für Ihren Compute-Node] In vSphere.
. Um einer vorhandenen Basisressource ein Controller Asset (vCenter), einen Computing Node (ESXi) oder eine Hardware (BMC) hinzuzufügen, wählen Sie eine der folgenden Optionen aus:
+
[cols="40,60"]
|===
| Option | Beschreibung 


| POST /Assets/{Asset_id}/Controller  a| 
.. Öffnen Sie die MNODE-Service-REST-API-UI auf dem Management-Node:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
+
... Wählen Sie *autorisieren* aus, und füllen Sie Folgendes aus:
+
.... Geben Sie den Benutzernamen und das Passwort für den Cluster ein.
.... Geben Sie die Client-ID als ein `mnode-client`.
.... Wählen Sie *autorisieren*, um eine Sitzung zu starten.
.... Schließen Sie das Fenster.




.. Wählen Sie *POST /Assets/{Asset_id}/Controllers* aus.
.. Wählen Sie *Probieren Sie es aus*.
.. Geben Sie die übergeordnete Basis-Asset-ID in das Feld *Asset_id* ein.
.. Fügen Sie die erforderlichen Werte der Nutzlast hinzu.
.. Wählen Sie *Ausführen*.




| POST /Assets/{Asset_id}/Compute-Nodes  a| 
.. Öffnen Sie die MNODE-Service-REST-API-UI auf dem Management-Node:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
+
... Wählen Sie *autorisieren* aus, und füllen Sie Folgendes aus:
+
.... Geben Sie den Benutzernamen und das Passwort für den Cluster ein.
.... Geben Sie die Client-ID als ein `mnode-client`.
.... Wählen Sie *autorisieren*, um eine Sitzung zu starten.
.... Schließen Sie das Fenster.




.. Wählen Sie *POST /Assets/{Asset_id}/Compute-Nodes* aus.
.. Wählen Sie *Probieren Sie es aus*.
.. Geben Sie im Feld *Asset_id* die übergeordnete Basis-Asset-ID ein, die Sie in einem früheren Schritt kopiert haben.
.. Führen Sie in der Nutzlast folgende Schritte aus:
+
... Geben Sie die Management-IP für den Node im ein `ip` Feld.
... Für `hardwareTag`Geben Sie den Hardware-Tag-Wert ein, den Sie in einem früheren Schritt gespeichert haben.
... Geben Sie bei Bedarf andere Werte ein.


.. Wählen Sie *Ausführen*.




| POST /Assets/{Asset_id}/Hardware-Nodes  a| 
.. Öffnen Sie die MNODE-Service-REST-API-UI auf dem Management-Node:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
+
... Wählen Sie *autorisieren* aus, und füllen Sie Folgendes aus:
+
.... Geben Sie den Benutzernamen und das Passwort für den Cluster ein.
.... Geben Sie die Client-ID als ein `mnode-client`.
.... Wählen Sie *autorisieren*, um eine Sitzung zu starten.
.... Schließen Sie das Fenster.




.. Wählen Sie *POST /Assets/{Asset_id}/Hardware-Nodes* aus.
.. Wählen Sie *Probieren Sie es aus*.
.. Geben Sie die übergeordnete Basis-Asset-ID in das Feld *Asset_id* ein.
.. Fügen Sie die erforderlichen Werte der Nutzlast hinzu.
.. Wählen Sie *Ausführen*.


|===




== Weitere Informationen

https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]
