---
sidebar: sidebar 
permalink: docs/task_nde_select_net_topology.html 
summary: Erfahren Sie, wie Sie VMware vSphere während der NetApp HCI Implementierung konfigurieren. 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= Wählen Sie eine Netzwerktopologie aus
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: netapp, hci, netapp deployment engine, deployment, vsphere


[role="lead"]
Bei der Verkabelung von NetApp HCI-Knoten haben Sie die Möglichkeit, unterschiedliche Netzwerkkabelkonfigurationen je nach Ihren Anforderungen zu verwenden. Für jeden Computing-Node können Sie alle sechs Netzwerkports mit unterschiedlichen Traffic-Typen verwenden, die jedem Port-Paar zugewiesen sind. Alternativ können Sie zwei Ports verwenden, wobei alle Arten von Datenverkehr den Ports zugewiesen sind. Storage-Nodes verwenden die standardmäßige Konfiguration mit vier Kabeln. Ihre Auswahl beeinflusst, welche Compute-Nodes im Inventar ausgewählt werden können.

.Was Sie benötigen
Bei Auswahl der zwei-Kabel-Netzwerktopologie für Computing-Nodes sollten folgende Anforderungen berücksichtigt werden:

* Sie haben eine VMware vSphere Enterprise Plus-Lizenz, die Sie nach Abschluss der Bereitstellung anwenden können.
* Sie haben überprüft, ob die Konfiguration Ihres Netzwerks und Ihrer Netzwerk-Switches korrekt ist.
* Für Storage- und vMotion-Netzwerke ist VLAN-Tagging für alle Computing- und Storage-Nodes erforderlich.


.Schritte
. Wählen Sie auf der Seite *Netzwerktopologie* eine Computing-Node-Topologie aus, die sich an die von Ihnen installierte Compute-Nodes für NetApp HCI eignet:
+
** *6 Kabeloption*: Die Option mit sechs Kabeln bietet für jeden Verkehrstyp (Verwaltung, virtuelle Maschine und Speicher) dedizierte Ports. Optional können Sie vSphere Distributed Switch (VDS) aktivieren. Durch Aktivieren von VDS wird ein verteilter Switch konfiguriert, der ein vereinfachtes, zentralisiertes Management der Netzwerkkonfiguration für Virtual Machines nach Abschluss der NetApp HCI-Implementierung ermöglicht. Wenn Sie diese Option aktivieren, müssen Sie nach der Bereitstellung über eine vSphere Enterprise Plus-Lizenz verfügen.
** *2 Kabeloption*: Die zwei-Kabel-Option kombiniert Management, virtuelle Maschine und Speicherverkehr auf zwei verbundenen Ports. Für diese Verkabelungsoption ist VDS erforderlich, und sie wird automatisch aktiviert. Sie müssen eine vSphere Enterprise Plus-Lizenz nach der Bereitstellung anwenden können.


. Bei einigen Kabeloptionen werden mehrere Ansichten auf der Rückseite der verschiedenen Node-Hardware angezeigt. Gehen Sie durch die Ansichten auf der Rückseite, um zu sehen, wie die Netzwerkkabel für das spezifische Node-Modell und die Kabeloption angeschlossen werden.
. Klicken Sie anschließend auf *Weiter*.


[discrete]
== Weitere Informationen

* link:firmware_driver_versions.html["Unterstützte Firmware- und ESXi-Treiberversionen für NetApp HCI und Firmware-Versionen für NetApp HCI Storage Nodes"]

