---
sidebar: sidebar 
permalink: docs/task_hci_upgrade_all_vsphere.html 
summary: Sie können VMware Komponenten für ein NetApp HCI-Upgrade durchführen und weitere Schritte zur Neuinstallation des vCenter Plug-ins Unternehmen. 
keywords: netapp, hci, vSphere components, upgrade, vCenter, ESXi 
---
= Aktualisieren Sie Ihre vSphere Komponenten für ein NetApp HCI System mit dem Element Plug-in für vCenter Server
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn Sie die VMware vSphere Komponenten Ihrer NetApp HCI Installation aktualisieren, sind für das Element Plug-in für vCenter Server einige zusätzliche Schritte erforderlich.

.Schritte
. Bei vCSA Upgrades https://docs.netapp.com/us-en/vcp/vcp_task_qossioc.html#clear-qossioc-settings["Löschen"^] QoSSIOC-Einstellungen im Plug-in (*NetApp Element-Konfiguration > QoSSIOC-Einstellungen*). Das Feld * QoSSIOC Status* wird angezeigt `Not Configured` Nach Abschluss des Vorgangs.
. Für Upgrades von vCSA und Windows https://docs.netapp.com/us-en/vcp/task_vcp_unregister.html["Deregistrieren"^] Das Plug-in vom vCenter Server, mit dem es über das Registrierungsprogramm verknüpft ist.
. https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vcenter.upgrade.doc/GUID-7AFB6672-0B0B-4902-B254-EE6AE81993B2.html["Aktualisieren Sie vSphere einschließlich vCenter Server, ESXi, VMs und anderen VMware Komponenten"^].
+
[IMPORTANT]
====
Sie sollten ein Upgrade auf das NetApp Element Plug-in für vCenter Server 5.0 oder höher durchführen, damit Sie das Plug-in mit VMware vCenter 7.0 Update 3 bereitstellen können, ohne eine Problemumgehung anwenden zu müssen.

Mit dem Element Plug-in für vCenter Server 4.x kann das Plug-in 4.x bei einem Upgrade auf VMware vCenter Server 7.0 Update 3 nicht bereitgestellt werden. Informationen zur Lösung dieses Problems mit Spring Framework 4 finden Sie unter https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/vCenter_plug-in_deployment_fails_after_upgrading_vCenter_to_version_7.0_U3["Diesen KB-Artikel"^].

====
+

NOTE: Wenn Sie ESXi für Compute-Nodes für einen https://www.netapp.com/pdf.html?item=/media/9489-tr-4823.pdf["Cluster mit zwei Nodes"^] aktualisieren, aktualisieren Sie jeweils nur einen Compute-Node, sodass nur ein Witness-Node vorübergehend nicht verfügbar ist und das Cluster-Quorum beibehalten werden kann.

. https://docs.netapp.com/us-en/vcp/vcp_task_getstarted.html#register-the-plug-in-with-vcenter["Registrieren"^] Das Element Plug-in für vCenter Server erneut mit vCenter.
. https://docs.netapp.com/us-en/vcp/vcp_task_getstarted.html#add-storage-clusters-for-use-with-the-plug-in["Fügen Sie Cluster hinzu"^] Verwenden des Plug-ins.
. https://docs.netapp.com/us-en/vcp/vcp_task_getstarted.html#configure-qossioc-settings-using-the-plug-in["Konfigurieren Sie die QoSSIOC-Einstellungen"^] Verwenden des Plug-ins.
. https://docs.netapp.com/us-en/vcp/vcp_task_qossioc.html#enabling-qossioc-automation-on-datastores["QoSSIOC aktivieren"^] Bei allen durch das Plug-in kontrollierten Datenspeichern.




== Weitere Informationen

* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]
* https://www.netapp.com/pdf.html?item=/media/9489-tr-4823.pdf["Technischer Bericht: NetApp HCI Two-Node Storage Cluster"^]

