---
sidebar: sidebar 
permalink: docs/task_hcc_upgrade_compute_firmware_ansible.html 
summary: Für H-Series Computing-Nodes bietet NetApp eine Ansible-Rolle, die Sie bei der Automatisierung der Firmware-Aktualisierung für Hardwarekomponenten wie BMC, BIOS und NIC unterstützt. 
keywords: netapp, hci, on premise, cluster, element, compute node, ansible upgrade, upgrade role 
---
= Automatisieren Sie Upgrades der Computing-Node-Firmware mit Ansible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können die System-Firmware auf NetApp HCI Compute-Nodes aktualisieren, einschließlich Firmware für Komponenten wie BMC, BIOS und NIC mithilfe von Workflows in NetApp Hybrid Cloud Control. Bei Installationen mit großen Computing-Clustern können die Workflows mithilfe von Ansible automatisiert werden, um ein Rolling Upgrade des gesamten Clusters durchzuführen.


NOTE: NetApp bietet die Ansible-Rolle zur Automatisierung von Computing-Node-Firmware-Upgrades. Die Automatisierung ist eine zusätzliche Komponente, die zusätzliche Einrichtung und Softwarekomponenten erforderlich macht. Änderungen der Ansible Automatisierung werden nur in Verbindung mit Mühe unterstützt.


NOTE: Die Ansible-Rolle für Upgrades kann nur auf Computing-Nodes der NetApp HCI H-Serie ausgeführt werden. Sie können diese Rolle nicht für ein Upgrade von Computing-Nodes von Drittanbietern verwenden.

.Was Sie und#8217;ll benötigen
* *Vorbereitung und Voraussetzungen für Firmware-Upgrades*: Ihre NetApp HCI-Installation muss für das Firmware-Upgrade bereit sein, wie in der Anleitung für beschrieben link:task_hcc_upgrade_compute_node_firmware.html["Firmware-Upgrades werden durchgeführt"].
* *Bereitschaft zur Durchführung der Automatisierung auf Ansible-Steuerungsknoten*: Ein physischer oder virtueller Server zur Ausführung der Firmware-Update-Automatisierung in Ansible.


In einer Produktionsumgebung sollten Computing-Nodes in einem Cluster einzeln oder nacheinander in einer NetApp HCI Installation aktualisiert werden. APIs in NetApp Hybrid Cloud Control koordinieren den allgemeinen Upgrade der Computing-Node-Firmware für einen einzelnen Computing-Node. Dazu gehören auch Zustandsprüfungen, Wartungsaufgaben von ESXi auf den Computing-Nodes und Neustart des Computing-Node zur Anwendung der Firmware-Upgrades. Die Ansible-Rolle bietet die Möglichkeit, das Firmware-Upgrade für eine Gruppe von Computing-Nodes oder ganzen Clustern zu orchestrieren.

Navigieren Sie zum, um zu beginnen https://github.com/NetApp-Automation/nar_compute_firmware_upgrade["NetApp Ansible Repository auf GitHub"^] Und laden Sie die herunter `nar_compute_nodes_firmware_upgrades` Rolle und Dokumentation:

[discrete]
== Weitere Informationen

* https://www.netapp.com/hybrid-cloud/hci-documentation/["Seite „NetApp HCI Ressourcen“"^]

