---
sidebar: sidebar 
permalink: docs/task_nde_configure_credentials.html 
summary: Erfahren Sie, wie Sie VMware vSphere während der NetApp HCI Implementierung konfigurieren. 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= NetApp HCI-Anmeldedaten werden konfiguriert
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: netapp, hci, netapp deployment engine, deployment, vsphere, vcenter, credentials, user accounts, administrator


[role="lead"]
Während der Implementierung definieren Sie einen Satz von Zugangsdaten, die in der neu implementierten VMware vSphere Umgebung, den NetApp HCI Computing- und Storage-Ressourcen und dem Management-Node verwendet werden sollen. Wenn Sie NetApp HCI in einer vorhandenen vSphere Umgebung implementieren, werden diese Anmeldedaten nicht auf den vorhandenen vCenter Server angewendet.

.Über diese Aufgabe
Beachten Sie folgende Punkte zu den in der NetApp HCI Deployment Engine festgelegten Anmeldedaten:

* *NetApp Hybrid Cloud Control (HCC) oder Element UI*: Um sich bei der erfolgreichen Implementierung bei NetApp HCC oder der Element User Interface anzumelden, verwenden Sie den in diesem Implementierungsschritt angegebenen Benutzernamen und das Passwort.
* *VMware vCenter*: Um sich bei vCenter anzumelden (falls im Rahmen der Bereitstellung installiert), verwenden Sie den Benutzernamen mit dem Suffix `@vsphere.local` Oder die integrierte `Administrator@vsphere.local` Benutzerkonto und das in diesem Bereitstellungsschritt angegebene Passwort.
* *VMware ESXi*: Um sich bei ESXi auf den Rechner-Knoten anzumelden, verwenden Sie den Benutzernamen `root` Und dasselbe Passwort, das in diesem Implementierungsschritt angegeben wurde.


Bei der Interaktion mit VMware vCenter Instanzen nutzt NetApp Hybrid Cloud Control eine der folgenden Komponenten:

* Die integrierte `Administrator@vsphere.local` Benutzerkonto auf der im Rahmen der Implementierung installierten vCenter Instanz.
* Die vCenter Zugangsdaten, über die die NetApp HCI Implementierung mit einem vorhandenen VMware vCenter Server verbunden wurde.


.Schritte
. Geben Sie auf der Seite *Anmeldeinformationen* einen Benutzernamen in das Feld *Benutzername* ein.
. Geben Sie im Feld *Passwort* ein Passwort ein. Das Passwort muss den Kennwortkriterien entsprechen, die im Feld *Passwort muss enthalten* angezeigt werden.
. Bestätigen Sie das Passwort im Feld *Passwort erneut eingeben*.
. Klicken Sie Auf *Weiter*.


[discrete]
== Weitere Informationen

* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Firmware_and_driver_versions_in_NetApp_HCI_and_NetApp_Element_software["Firmware- und Treiberversionen in NetApp HCI- und NetApp Element-Software"^]
* Informationen zum späteren Aktualisieren der vCenter- und ESXi-Anmeldedaten finden Sie unter link:task_hci_credentials_vcenter_esxi.html["Aktualisieren der vCenter- oder ESXi-Anmeldedaten"].

