---
sidebar: sidebar 
permalink: docs/task_hci_credentials_vcenter_esxi.html 
summary: Bei einer NetApp HCI Installation können die Anmeldedaten für vCenter sowie für ESXi Hosts für einen Computing-Node geändert werden, der von NetApp Hybrid Cloud Control gemanagt wird. 
keywords: netapp, hci, password, credential, vcenter, esxi, hybrid cloud control 
---
= Aktualisieren der vCenter- und ESXi-Anmeldedaten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn Sie Ihre Anmeldedaten in vCenter- und ESXi-Hosts ändern, müssen Sie die vollständigen Funktionen von NetApp Hybrid Cloud Control für Ihre NetApp HCI-Installation beibehalten. Auch müssen Sie diese Anmeldedaten im Asset-Service auf dem Management-Node aktualisieren.

.Über diese Aufgabe
NetApp Hybrid Cloud Control kommuniziert mit vCenter und den einzelnen Computing-Nodes mit VMware vSphere ESXi, um Informationen zum Dashboard abzurufen und Rolling Upgrades von Firmware, Software und Treibern zu vereinfachen. NetApp Hybrid Cloud Control und seine zugehörigen Services auf dem Management-Node authentifizieren sich mit Anmeldeinformationen (Benutzername/Passwort) gegen VMware vCenter und ESXi.

Wenn die Kommunikation zwischen diesen Komponenten fehlschlägt, zeigen NetApp Hybrid Cloud Control und vCenter bei einem Authentifizierungsprobleme Fehlermeldungen an. Bei NetApp Hybrid Cloud Control wird ein rotes Fehlerbanner angezeigt, wenn es nicht mit der zugehörigen VMware vCenter Instanz in der NetApp HCI Installation kommunizieren kann. VMware vCenter zeigt ESXi Kontosperrmeldungen für einzelne ESXi Hosts dank NetApp Hybrid Cloud Control mit veralteten Zugangsdaten an.

Der Management-Node in NetApp HCI bezeichnet diese Komponenten mit den folgenden Namen:

* „Controller Assets“ sind vCenter Instanzen, die Ihrer NetApp HCI Installation zugeordnet sind.
* „Compute-Node-Ressourcen“ sind die ESXi-Hosts in Ihrer NetApp HCI Installation.


Bei der Erstinstallation von NetApp HCI mit der NetApp Deployment Engine speicherte der Management-Node die Anmeldeinformationen für den administrativen Benutzer, den Sie für vCenter angegeben haben, und das „Root“-Account-Passwort auf ESXi Servern.



== Aktualisieren Sie das vCenter Passwort mithilfe der REST-API des Management-Node

Führen Sie die Schritte aus, um die Controller-Assets zu aktualisieren. Siehe link:task_mnode_edit_vcenter_assets.html["Vorhandene Controller-Assets können angezeigt oder bearbeitet werden"].



== Aktualisieren Sie das ESXi-Passwort mithilfe der REST-API des Management-Node

.Schritte
. Eine Übersicht über DIE REST-API-Benutzeroberfläche der Management-Node finden Sie im link:task_mnode_work_overview_API.html["Übersicht über DIE REST-API-Benutzeroberfläche der Management-Node"].
. Greifen Sie auf die REST-API-UI für Managementservices auf dem Management-Node zu:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
+
Ersetzen Sie <Management-Node-IP> durch die IPv4-Adresse des Management-Node im für NetApp HCI verwendeten Managementnetzwerk.

. Klicken Sie auf *autorisieren* oder auf ein Schloss-Symbol, und füllen Sie Folgendes aus:
+
.. Geben Sie den Benutzernamen und das Passwort für den NetApp SolidFire Cluster-Administrator ein.
.. Geben Sie die Client-ID als ein `mnode-client`.
.. Klicken Sie auf *autorisieren*, um eine Sitzung zu starten.
.. Schließen Sie das Fenster.


. Klicken Sie in DER REST API-Benutzeroberfläche auf *GET ​/Assets/Compute_Nodes*.
+
Hierdurch werden die Datensätze von Computing-Node-Assets abgerufen, die im Management-Node gespeichert werden.

+
Hier ist der direkte Link zu dieser API in der UI:

+
[listing]
----
https://<ManagementNodeIP>/mnode/#/assets/routes.v1.assets_api.get_compute_nodes
----
. Klicken Sie auf *Probieren Sie es aus*.
. Klicken Sie Auf *Ausführen*.
. Ermitteln Sie im Antwortkörper die Datensätze der Computing-Node-Assets, die aktualisierte Anmeldedaten benötigen. Sie können die Eigenschaften „ip“ und „Host_Name“ verwenden, um die richtigen ESXi-Host-Datensätze zu finden.
+
[listing]
----
"config": { },
"credentialid": <credential_id>,
"hardware_tag": <tag>,
"host_name": <host_name>,
"id": <id>,
"ip": <ip>,
"parent": <parent>,
"type": ESXi Host
----
+

NOTE: Im nächsten Schritt werden die Felder „Parent“ und „id“ im Datensatz „Compute Asset Record“ verwendet, um auf den zu aktualisienden Datensatz Bezug zu nehmen.

. Konfiguration der spezifischen Computing-Node-Ressource:
+
.. Klicken Sie auf *PUT /Assets/{Asset_id}/Compute-Nodes/{Compute_id}*.
+
Hier ist der direkte Link zur API in der UI:

+
[listing]
----
https://<ManagementNodeIP>/mnode/#/assets/routes.v1.assets_api.put_assets_compute_id
----
.. Klicken Sie auf *Probieren Sie es aus*.
.. Geben Sie die „Asset_id“ mit den „übergeordneten“ Informationen ein.
.. Geben Sie die „Compute_id“ mit der „id“-Information ein.
.. Ändern Sie den Anfraentext in der Benutzeroberfläche, um nur die Kennwortparameter und die Parameter für den Benutzernamen im Datensatz für die Rechnungsanteile zu aktualisieren:
+
[listing]
----
{
"password": "<password>",
"username": "<username>"
}
----
.. Klicken Sie Auf *Ausführen*.
.. Überprüfen Sie, ob es sich bei der Antwort um HTTP 200 handelt, was bedeutet, dass die neuen Anmeldeinformationen im Datensatz der referenzierten Rechnungs-Anlage gespeichert wurden


. Wiederholen Sie die vorherigen beiden Schritte für zusätzliche Computing-Node-Ressourcen, die mit einem neuen Passwort aktualisiert werden müssen.
. Navigieren Sie zu https://<mNode_ip>/inventory/1/[].
+
.. Klicken Sie auf *autorisieren* oder auf ein Schloss-Symbol, und füllen Sie Folgendes aus:
+
... Geben Sie den Benutzernamen und das Passwort für den NetApp SolidFire Cluster-Administrator ein.
... Geben Sie die Client-ID als ein `mnode-client`.
... Klicken Sie auf *autorisieren*, um eine Sitzung zu starten.
... Schließen Sie das Fenster.


.. Klicken Sie in DER REST API UI auf *GET /Installations*.
.. Klicken Sie auf *Probieren Sie es aus*.
.. Wählen Sie in der Dropdown-Liste Beschreibung aktualisieren die Option *true* aus.
.. Klicken Sie Auf *Ausführen*.
.. Überprüfen Sie, ob die Antwort HTTP 200 ist.


. Warten Sie ca. 15 Minuten, bis die Meldung Kontosperrung in vCenter verschwindet.




== Weitere Informationen

* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]

